### ISSUE TITLE
[Travis CI]: Adding python 3.6, 3,7 , 3,8 environments in the travis.yml file

### ISSUE THREAD

**Issue by mritunjaysharma394** [mritunjaysharma394/sedpy#2]
It is always a nice idea to test the builds for different environments. Locally - it works fine on each environment as mentioned in the badges. However, it will be nicer if we can add and test the same on Travis CI :sparkles: 

Right now: 
.travis.yml looks like

```language: python
install:
  - pip install tox
matrix:
  include:
    - python: 2.7
      env:
       - TOX_ENV=py27
    - python: 3.5
      env:
        - TOX_ENV=py35
script: tox -e $TOX_ENV
```

This file should give you the hint on how to add build tests for python 3.6, 3,7, and 3.8. For any queries, feel free to ping.

**Comment by codequinn** [comment]
Working on it
