### ISSUE TITLE
[Travis CI]: Travis CI file .travis.yml is not parsing for the build. 

### ISSUE THREAD

**Issue by mritunjaysharma394** [mritunjaysharma394/sedpy#6]
This issue seems to be tabs vs spaces issue :weary: 

Looking at the first hand and checking on yaml lint tool, I got something like this:

 `Did not find expected '-' indicator while parsing a block collection at line 6 column 5`

It looks to be a good first issue. 
To check whether travis.yml will work (lints) properly or not, you can make use of this: http://www.yamllint.com/ :eyes:

**Comment by vermakhushboo** [comment]
I'd like to take this up.
