### ISSUE TITLE
Designing a logo for sedpy.

### ISSUE THREAD

**Issue by mritunjaysharma394** [mritunjaysharma394/sedpy#8]
It's your time designers :clinking_glasses:  As you all know, we don't have an official logo for sedpy. Can we all work on that? Of course :partying_face: 

If anyone likes to contribute to this, please comment your designs in this issue.
The logo image should be in SVG format(simple, minimalistic).

**Comment by ananya224** [comment]
Hey Mritunjay,
I came up with these two logo designs for SedPy. These are simple and minimal in their design approach. Would really appreciate a feedback.
![2](https://user-images.githubusercontent.com/60890014/92006304-2d407b80-ed62-11ea-9206-065acbf6fcff.png)
![3](https://user-images.githubusercontent.com/60890014/92006313-2f0a3f00-ed62-11ea-99d2-f5dcd42c26df.png)

**Comment by mritunjaysharma394** [comment]
> Hey Mritunjay,
> I came up with these two logo designs for SedPy. These are simple and minimal in their design approach. Would really appreciate a feedback.
> ![2](https://user-images.githubusercontent.com/60890014/92006304-2d407b80-ed62-11ea-9206-065acbf6fcff.png)
> ![3](https://user-images.githubusercontent.com/60890014/92006313-2f0a3f00-ed62-11ea-99d2-f5dcd42c26df.png)

Hey, @ananya224 , Thank you so much for your time, I like the first logo for our project
